import type { PropsWithChildren } from 'react'

import { ArticlePageLayout } from '@/components/blog/ArticlePageLayout'
import type { PageParams } from '@/lib/core/navigation/types'

/**
 * This page does note generate routes directly. It is used:
 * - to create an entry in the autogenerated route manifest
 * - to wrap article pages via mdx webpack loader
 *
 * That's why `getStaticPaths` is not needed, why the page component
 * accepts a `children` prop, and why `metadata` is in scope (it is added by
 * `@stefanprobst/remark-extract-yaml-frontmatter/mdx`).
 */

export type ArticlePageParamsInput = {
  id: string
}
export type ArticlePageParams = PageParams<ArticlePageParamsInput>
export type ArticlePageProps = Record<string, never>

export default function ArticlePage(props: PropsWithChildren<ArticlePageProps>): JSX.Element {
  /* @ts-expect-error Metadata is added via mdx loader. */
  return <ArticlePageLayout metadata={metadata}>{props.children}</ArticlePageLayout>
}
