# load_config_file: false

# site_url: http://localhost:3000
logo_url: /assets/images/logo.svg

local_backend: true
backend:
  name: github
  repo: stefanprobst/wibarab
  branch: main
  base_url: https://wibarab.acdh-dev.oeaw.ac.at
  auth_endpoint: api/auth/github
  auth_scope: public_repo

  # open_authoring: false
  # always_fork: true

  squash_merges: true
  commit_messages:
    create: 'content(cms): create {{collection}} "{{slug}}"'
    update: 'content(cms): update {{collection}} "{{slug}}"'
    delete: 'content(cms): delete {{collection}} "{{slug}}"'
    uploadMedia: 'content(cms): upload "{{path}}"'
    deleteMedia: 'content(cms): delete "{{path}}"'
    openAuthoring: '{{message}}'

publish_mode: editorial_workflow
media_folder: public/assets/cms/images
public_folder: /assets/cms/images
show_preview_links: false
editor:
  preview: false

collections:
  - name: sections
    label: Sections
    label_singular: Section
    format: frontmatter
    extension: mdx
    files:
      - name: about
        label: About the project
        file: src/components/home/About.mdx
        fields:
          - name: title
            label: Title
          - name: body
            label: Content
            widget: markdown

  - name: team
    label: Team
    label_singular: Team member
    identifier_field: name
    slug: '{{slug}}'
    # format: frontmatter
    format: json
    folder: src/components/home/team
    create: true
    fields:
      - name: name
        label: Name
      - name: email
        label: Email
      - name: bio
        # name: body
        label: Bio
        # widget: markdown
        widget: text

  - name: blog
    label: Blog
    label_singular: Article
    format: frontmatter
    extension: mdx
    folder: src/pages/blog
    create: true
    fields:
      - name: title
        label: Title
      - name: authors
        label: Authors
        widget: relation
        collection: team
        multiple: true
        value_field: '{{slug}}'
        search_fields: ['name']
        display_fields: ['{{name}}']
      - name: date
        label: Publication date
        widget: datetime
        date_format: DD/MM/YYYY
        time_format: false
        picker_utc: true
        default: ''
      - name: abstract
        label: Abstract
        widget: text
      - name: leadIn
        label: Lead in
        widget: text
      - name: featuredImage
        label: Featured image
        widget: image
      - name: body
        label: Content
        widget: markdown
